const config=window.MOSQUEE_CONFIG;const zone=config.timezone||'Indian/Reunion';const $=id=>document.getElementById(id);const CALENDAR_URL='./horaires_priere_zone_sud_reunion_complet.json';const ALTITUDE_CORRECTION={subh_sadiq:-3,lever_soleil:-3,zohr:0,asr:0,maghreb:3,isha:3};const ADMIN_KEY='anasAdminSettings';
const HIJRI_AR={Muharram:'محرم',Safar:'صفر','Rabi al-Awwal':'ربيع الأول','Rabi ath-Thani':'ربيع الآخر','Jumada al-Ula':'جمادى الأولى','Jumada ath-Thania':'جمادى الآخرة',Rajab:'رجب',"Sha'ban":'شعبان',Ramadan:'رمضان',Shawwal:'شوال',"Dhul Qi'dah":'ذو القعدة','Dhul Hijjah':'ذو الحجة'};const RUNSALAH_REF={date:'2026-08-13',day:28,month:'Safar',year:1448};
let calendar=[],prayers=[],sunriseTime='--:--',loadedDateKey='';function admin(){try{return JSON.parse(localStorage.getItem(ADMIN_KEY)||'{}')}catch(e){return{}}}document.title=`${config.mosqueName} — Horaires de prière`;document.querySelector('h1').textContent=config.mosqueName;document.querySelector('.brand-ar').textContent=config.mosqueNameArabic;$('location').textContent=config.location;
function localParts(date=new Date()){const x=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date);return Object.fromEntries(x.filter(p=>p.type!=='literal').map(p=>[p.type,p.value]))}
function parseTime(v){if(!v)return null;const[h=0,m=0,s=0]=v.split(':').map(Number);return{h,m,s}}function format24(v,period){const t=parseTime(v);if(!t)return'--:--';let h=t.h;if(period==='pm'&&h<12)h+=12;if(period==='am'&&h===12)h=0;return`${String(h).padStart(2,'0')}:${String(t.m).padStart(2,'0')}`}
function shiftMinutes(v,minutes){if(!v||v==='--:--')return v;const[h,m]=v.split(':').map(Number);let total=(h*60+m+minutes)%1440;if(total<0)total+=1440;return`${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}function corrected(v,period,key){return shiftMinutes(format24(v,period),ALTITUDE_CORRECTION[key]||0)}
function mosquePrayerTime(n,fallback){const a=admin();if(a.prayers?.[n])return a.prayers[n];const item=config.prayers?.find(p=>p.name===n);return item?.iqama||item?.time||fallback||'—'}
function buildPrayers(d){sunriseTime=corrected(d.lever_soleil,'am','lever_soleil');const adhan={Fajr:corrected(d.subh_sadiq,'am','subh_sadiq'),Dhuhr:corrected(d.zohr,'pm','zohr'),Asr:corrected(d.asr,'pm','asr'),Maghrib:corrected(d.maghreb,'pm','maghreb'),Isha:corrected(d.isha,'pm','isha')};return[{name:'Fajr',arabic:'الفجر',adhan:adhan.Fajr,prayer:mosquePrayerTime('Fajr',adhan.Fajr)},{name:'Dhuhr',arabic:'الظهر',adhan:adhan.Dhuhr,prayer:mosquePrayerTime('Dhuhr',adhan.Dhuhr)},{name:'Asr',arabic:'العصر',adhan:adhan.Asr,prayer:mosquePrayerTime('Asr',adhan.Asr)},{name:'Maghrib',arabic:'المغرب',adhan:adhan.Maghrib,prayer:adhan.Maghrib},{name:'Isha',arabic:'العشاء',adhan:adhan.Isha,prayer:mosquePrayerTime('Isha',adhan.Isha)}]}
function renderSolarInfo(d){if(!d)return;const starts=[['Fajr',corrected(d.subh_sadiq,'am','subh_sadiq')],['Dhuhr',corrected(d.zohr,'pm','zohr')],['Asr',corrected(d.asr,'pm','asr')],['Maghrib',corrected(d.maghreb,'pm','maghreb')],['Isha',corrected(d.isha,'pm','isha')]];const z=corrected(d.zohr,'pm','zohr'),before=shiftMinutes(z,-2),after=shiftMinutes(z,2);const st=$('solar-times'),zw=$('zenith-warning');if(st)st.innerHTML='<strong>DÉBUT DES PRIÈRES</strong> '+starts.map(([n,t])=>`<span>${n} <b>${t}</b></span>`).join('');if(zw)zw.textContent=`Zénith ${z} — ne pas prier de ${before} à ${after} (2 min avant et 2 min après).`}
function findDay(p=localParts()){return calendar.find(d=>+d.mois_numero===+p.month&&+d.jour===+p.day)}function timeForDate(v,p){const[h,m]=v.split(':').map(Number);return Date.UTC(+p.year,+p.month-1,+p.day,h-4,m)}function tomorrowParts(){const p=localParts();return localParts(new Date(Date.UTC(+p.year,+p.month-1,+p.day+1,8)))}function findNext(){const p=localParts(),now=Date.now();for(const prayer of prayers){const at=timeForDate(prayer.prayer,p);if(at>now)return{prayer,at}}const tp=tomorrowParts(),d=findDay(tp);if(d){const current=findDay(p),fajr=buildPrayers(d)[0];if(current)prayers=buildPrayers(current);return{prayer:fajr,at:timeForDate(fajr.prayer,tp)}}return null}
function render(){if(!prayers.length)return;const next=findNext()?.prayer.name;$('sunrise').textContent=sunriseTime;const a=admin();$('jumua-time').textContent=a.jumua||config.jumua||'—';$('prayer-grid').innerHTML=prayers.map(p=>`<article class="prayer ${p.name===next?'active':''}"><h2>${p.name}</h2><p class="arabic" lang="ar" dir="rtl">${p.arabic}</p><div class="prayer-main"><span class="time-label">PRIÈRE</span><time>${p.prayer}</time></div><p class="adhan-line"><span>ADHAN</span><strong>${p.adhan}</strong></p></article>`).join('');renderSolarInfo(findDay())}
function localDateISO(now=new Date()){const p=localParts(now);return`${p.year}-${p.month}-${p.day}`}function dateAtReunion(iso){return new Date(iso+'T00:00:00+04:00')}function hijriOut(day,month,year){return{fr:`${day} ${month} ${year} H`,ar:`${day} ${HIJRI_AR[month]||month} ${year} هـ`}}
function hijriDates(now){const a=admin();if(a.hijri?.start&&a.hijri?.month&&a.hijri?.year){const start=dateAtReunion(a.hijri.start),current=dateAtReunion(localDateISO(now));const day=Math.floor((current-start)/86400000)+1;if(day>=1&&day<=31)return hijriOut(day,a.hijri.month,a.hijri.year)}const current=dateAtReunion(localDateISO(now)),ref=dateAtReunion(RUNSALAH_REF.date),delta=Math.floor((current-ref)/86400000),day=RUNSALAH_REF.day+delta;if(day>=1&&day<=30)return hijriOut(day,RUNSALAH_REF.month,RUNSALAH_REF.year);try{return{fr:new Intl.DateTimeFormat('fr-FR-u-ca-islamic',{timeZone:zone,day:'numeric',month:'long',year:'numeric'}).format(now).replace(/AH|هـ/g,'H'),ar:new Intl.DateTimeFormat('ar-u-ca-islamic',{timeZone:zone,day:'numeric',month:'long',year:'numeric'}).format(now)}}catch(e){return{fr:'—',ar:'—'}}}
function loadToday(force=false){const p=localParts(),key=`${p.month}-${p.day}`;if(!force&&key===loadedDateKey)return true;const d=findDay(p);if(!d)return false;prayers=buildPrayers(d);loadedDateKey=key;render();return true}function update(){const now=new Date();loadToday();const d=findDay();prayers=buildPrayers(d||{});$('clock').textContent=new Intl.DateTimeFormat('fr-FR',{timeZone:zone,hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(now);$('today').textContent=new Intl.DateTimeFormat('fr-FR',{timeZone:zone,weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(now);const hd=hijriDates(now);$('hijri-date').textContent=hd.fr;const ar=$('hijri-date-ar');if(ar)ar.textContent=hd.ar;if(new Date().getSeconds()===0)render()}
async function init(){try{const r=await fetch(CALENDAR_URL,{cache:'no-store'});if(!r.ok)throw Error(r.status);const data=await r.json();calendar=Array.isArray(data.horaires)?data.horaires:[];if(!calendar.length||!loadToday(true))throw Error('Calendrier indisponible');update();setInterval(update,1000)}catch(e){console.error(e);$('prayer-grid').innerHTML='<article class="prayer"><h2>Horaires indisponibles</h2></article>'}}init();