(function(){
'use strict';
var config=window.MOSQUEE_CONFIG||{};var sb=window.MOSQUEE_SUPABASE||{};var calendar=[],settings={},announcements=[],announcementIndex=0,announcementShowing=false,announcementTimer=null;var corrections={subh_sadiq:-3,lever_soleil:-3,zohr:0,asr:0,maghreb:3,isha:3};var DISPLAY_SETTINGS_URL='https://volmqjjvcytkojbfvvfz.supabase.co/functions/v1/public-display-settings';var ANNOUNCEMENTS_URL='https://volmqjjvcytkojbfvvfz.supabase.co/functions/v1/public-announcements';
function $(id){return document.getElementById(id)}function pad(n){return n<10?'0'+n:String(n)}function reunionNow(){return new Date(Date.now()+4*60*60*1000)}function parts(){var d=reunionNow();return{year:d.getUTCFullYear(),month:d.getUTCMonth()+1,day:d.getUTCDate(),hour:d.getUTCHours(),minute:d.getUTCMinutes(),second:d.getUTCSeconds(),weekday:d.getUTCDay()}}
function fmt(v,pm){if(!v)return'--:--';var a=v.split(':'),h=parseInt(a[0],10),m=parseInt(a[1],10);if(pm&&h<12)h+=12;if(!pm&&h===12)h=0;return pad(h)+':'+pad(m)}function shift(v,n){if(!v||v==='--:--')return v;var a=v.split(':'),t=parseInt(a[0],10)*60+parseInt(a[1],10)+n;t=(t+1440)%1440;return pad(Math.floor(t/60))+':'+pad(t%60)}function corrected(v,pm,key){return shift(fmt(v,pm),corrections[key]||0)}
function findDay(){var p=parts(),i,d;for(i=0;i<calendar.length;i++){d=calendar[i];if(parseInt(d.mois_numero,10)===p.month&&parseInt(d.jour,10)===p.day)return d}return null}function cfgPrayer(name,fallback){var i,p;if(settings.prayers&&settings.prayers[name])return settings.prayers[name];for(i=0;i<(config.prayers||[]).length;i++){p=config.prayers[i];if(p.name===name)return p.iqama||p.time||fallback}return fallback}function adhan(name,fallback){if(name==='Maghrib')return fallback;if(settings.adhan&&settings.adhan[name])return settings.adhan[name];if(config.adhan&&config.adhan[name])return config.adhan[name];return fallback}
function hijriSource(){return settings.hijri&&settings.hijri.month?settings.hijri:(config.hijri||{})}function hijriText(){var h=hijriSource();if(!h)return'—';if(typeof h==='string')return h;if(h.text)return h.text;if(h.date)return h.date;if(h.label)return h.label;if(h.start&&h.month&&h.year){var a=h.start.split('-');if(a.length===3){var start=Date.UTC(parseInt(a[0],10),parseInt(a[1],10)-1,parseInt(a[2],10)),p=parts(),today=Date.UTC(p.year,p.month-1,p.day),day=Math.floor((today-start)/86400000)+1;if(day>0&&day<=30)return day+' '+h.month+' '+h.year+' هـ'}}return'—'}function mins(v){if(!v||v.indexOf(':')<0)return 9999;var a=v.split(':');return parseInt(a[0],10)*60+parseInt(a[1],10)}
function loadLocalSettings(){try{var s=localStorage.getItem('anas_mosquee_settings');if(s)settings=JSON.parse(s)||{}}catch(e){}}function saveLocalSettings(){try{localStorage.setItem('anas_mosquee_settings',JSON.stringify(settings))}catch(e){}}function loadLocalCalendar(){try{var s=localStorage.getItem('anas_mosquee_calendar');if(s){var d=JSON.parse(s);if(d&&d.length){calendar=d;return true}}}catch(e){}return false}function saveLocalCalendar(){try{if(calendar&&calendar.length)localStorage.setItem('anas_mosquee_calendar',JSON.stringify(calendar))}catch(e){}}
function prayerData(){var d=findDay(),out=[],names=['Fajr','Dhuhr','Asr','Maghrib','Isha'],auto,i,n,a,q,p=parts(),now=p.hour*60+p.minute,next=-1;if(!d)return{times:[],next:0};auto={Fajr:corrected(d.subh_sadiq,false,'subh_sadiq'),Dhuhr:corrected(d.zohr,true,'zohr'),Asr:corrected(d.asr,true,'asr'),Maghrib:corrected(d.maghreb,true,'maghreb'),Isha:corrected(d.isha,true,'isha')};for(i=0;i<names.length;i++){n=names[i];a=adhan(n,auto[n]);q=n==='Maghrib'?a:cfgPrayer(n,a);out.push({name:n,a:a,q:q,auto:auto[n]});if(next<0&&mins(q)>now)next=i}if(next<0)next=0;return{times:out,next:next}}
function render(){var d=findDay();if(!d)return;var pd=prayerData(),times=pd.times,next=pd.next,html='',starts='',i,n,a,q;$('sunrise').textContent=corrected(d.lever_soleil,false,'lever_soleil');$('jumua-time').textContent=settings.jumua||config.jumua||'—';if($('hijri-date'))$('hijri-date').textContent=hijriText();for(i=0;i<times.length;i++){n=times[i].name;a=times[i].a;q=times[i].q;html+='<article class="prayer'+(i===next?' active':'')+'"><h2>'+n+'</h2><div class="prayer-main"><time>'+q+'</time></div><p class="adhan-line"><span class="adhan-icon">🔊</span><strong>'+a+'</strong></p></article>';starts+='<span>'+n+' <b>'+times[i].auto+'</b></span>'}$('prayer-grid').innerHTML=html;if($('solar-times'))$('solar-times').innerHTML='<strong>DÉBUT DES PRIÈRES</strong> '+starts;if(announcementShowing)renderAnnouncementPrayerBar()}
function tick(){var p=parts();if($('clock'))$('clock').textContent=pad(p.hour)+':'+pad(p.minute)+':'+pad(p.second);var days=['dimanche','lundi','mardi','mercredi','jeudi','vendredi','samedi'],months=['janvier','février','mars','avril','mai','juin','juillet','août','septembre','octobre','novembre','décembre'];if($('today'))$('today').textContent=days[p.weekday]+' '+p.day+' '+months[p.month-1]+' '+p.year;if($('announcement-clock'))$('announcement-clock').textContent=pad(p.hour)+':'+pad(p.minute)}
function xhr(url,cb){var x=new XMLHttpRequest();x.open('GET',url,true);x.onreadystatechange=function(){if(x.readyState===4)cb(x.status,x.responseText)};x.onerror=function(){cb(0,'')};x.send(null)}
function acceptCalendar(text){try{var data=JSON.parse(text);if(data&&data.horaires&&data.horaires.length){calendar=data.horaires;saveLocalCalendar();render();return true}}catch(e){}return false}function loadCalendar(){xhr('./horaires_priere_zone_sud_reunion_complet.json?v=20260901offline6',function(status,text){if(status>=200&&status<300&&acceptCalendar(text))return;if(loadLocalCalendar())render()})}
function loadSettings(){xhr(DISPLAY_SETTINGS_URL+'?t='+new Date().getTime(),function(status,text){if(status>=200&&status<300){try{var data=JSON.parse(text);if(data&&data.prayers){settings=data;saveLocalSettings();render()}}catch(e){}}})}
function loadAnnouncements(){xhr(ANNOUNCEMENTS_URL+'?t='+new Date().getTime(),function(status,text){if(status>=200&&status<300){try{var d=JSON.parse(text);announcements=d&&d.announcements?d.announcements:[];try{localStorage.setItem('anas_mosquee_announcements',JSON.stringify(announcements))}catch(e){}}catch(e){}}else{try{var s=localStorage.getItem('anas_mosquee_announcements');if(s)announcements=JSON.parse(s)||[]}catch(e){}}})}
function ensureAnnouncementLayer(){if($('announcement-layer'))return;var e=document.createElement('div');e.id='announcement-layer';e.innerHTML='<div class="announcement-main"><div class="announcement-badge">ANNONCE IMPORTANTE</div><div class="announcement-content"><img id="announcement-image" alt=""><div class="announcement-text"><h2 id="announcement-title"></h2><p id="announcement-message"></p></div></div></div><div class="announcement-bottom"><span id="announcement-clock">--:--</span><div id="announcement-prayers"></div></div>';document.body.appendChild(e)}
function renderAnnouncementPrayerBar(){var box=$('announcement-prayers'),pd=prayerData(),h='',i;if(!box)return;for(i=0;i<pd.times.length;i++)h+='<span class="ann-prayer'+(i===pd.next?' next':'')+'"><b>'+pd.times[i].name+'</b> '+pd.times[i].q+'</span>';box.innerHTML=h}
function showAnnouncement(){if(announcementShowing||!announcements.length)return;ensureAnnouncementLayer();var a=announcements[announcementIndex%announcements.length];announcementIndex=(announcementIndex+1)%announcements.length;$('announcement-title').textContent=a.title||'';$('announcement-message').textContent=a.message||'';var im=$('announcement-image');if(a.image_url){im.src=a.image_url;im.style.display='block'}else{im.style.display='none';im.src=''};renderAnnouncementPrayerBar();$('announcement-layer').style.display='flex';announcementShowing=true;var sec=parseInt(a.duration_seconds,10)||20;if(sec<10)sec=10;if(sec>60)sec=60;announcementTimer=setTimeout(hideAnnouncement,sec*1000)}function hideAnnouncement(){if($('announcement-layer'))$('announcement-layer').style.display='none';announcementShowing=false;announcementTimer=null}
document.title=(config.mosqueName||'Mosquée Anas Ibn Malik')+' — Horaires de prière';loadLocalSettings();loadLocalCalendar();tick();setInterval(tick,1000);if(calendar.length)render();loadSettings();loadCalendar();loadAnnouncements();setInterval(render,10000);setInterval(loadSettings,10000);setInterval(loadAnnouncements,30000);setTimeout(function(){showAnnouncement();setInterval(showAnnouncement,300000)},60000);if(window.addEventListener)window.addEventListener('online',function(){loadSettings();loadCalendar();loadAnnouncements()});
})();